#!/bin/bash

# Sets MacOS defaults
# https://macos-defaults.com/

# Set dock to autohide
defaults write com.apple.dock "autohide" -bool "true" && killall Dock

# Install oh my zsh 
# https://ohmyz.sh/
sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"